version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tutor-desk-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tutor_desk
    volumes:
      - mongodb_data:/data/db
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - tutor-desk-network

  tutor-desk-app:
    build: .
    container_name: tutor-desk-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODEB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: tutor_desk
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password123
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      MAIL_USERNAME: ${MAIL_USERNAME:}
      MAIL_PASSWORD: ${MAIL_PASSWORD:}
    depends_on:
      - mongodb
    networks:
      - tutor-desk-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: tutor-desk-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    depends_on:
      - mongodb
    networks:
      - tutor-desk-network

volumes:
  mongodb_data:
    driver: local

networks:
  tutor-desk-network:
    driver: bridge
